import {
  AVATAR_BASE,
  AVATAR_PARTS_COUNT,
  type Avatar,
  type AvatarParts,
} from "@twf/contracts";

/**
 * Player avatar:
 *
 * Source of truth:
 * - Backend generates a compact avatar string once per player when they join.
 * - Frontend only decodes and renders that value.
 *
 * Avatar string format:
 * - "<body>.<mouth>.<eyes>" (three base36 indices), e.g. "2.4.a"
 * - Order is always: body (bottom), mouth (middle), eyes (top).
 *
 * Asset loading:
 * - We use `import.meta.glob(..., { eager: true, import: "default" })` to load
 *   all matching PNGs and get their built URL strings.
 * - Files are sorted deterministically so index -> asset mapping is stable.
 *
 * If you add/remove avatar part PNGs:
 * - Update contract counts in `@twf/contracts`:
 *   `AVATAR_BODY_COUNT`, `AVATAR_MOUTH_COUNT`, `AVATAR_EYES_COUNT`.
 * - Bump both server and client to the same contracts commit so generated
 *   indices match rendered assets.
 */

type PlayerAvatarLayers = {
  bodySrc: string;
  mouthSrc: string;
  eyesSrc: string;
};

const BODY_ASSET_MODULES = import.meta.glob(
  "/src/assets/public/PlayerIcons/Bodies/*.png",
  {
    eager: true,
    import: "default",
  },
) as Record<string, string>;

const MOUTH_ASSET_MODULES = import.meta.glob(
  "/src/assets/public/PlayerIcons/Mouths/*.png",
  {
    eager: true,
    import: "default",
  },
) as Record<string, string>;

const EYE_ASSET_MODULES = import.meta.glob(
  "/src/assets/public/PlayerIcons/Eyes/*.png",
  {
    eager: true,
    import: "default",
  },
) as Record<string, string>;

/**
 * Produces a stable, deterministic asset order from Vite's glob map.
 * Keep this ordering logic aligned with backend avatar generation counts so
 * body/mouth/eyes indices resolve to the expected PNGs.
 */
function toOrderedAssetList(assetModules: Record<string, string>): string[] {
  return Object.entries(assetModules)
    .sort(([pathA], [pathB]) =>
      pathA.localeCompare(pathB, undefined, {
        numeric: true,
        sensitivity: "base",
      }),
    )
    .map(([, src]) => src);
}

const BODY_ASSETS = toOrderedAssetList(BODY_ASSET_MODULES);
const MOUTH_ASSETS = toOrderedAssetList(MOUTH_ASSET_MODULES);
const EYE_ASSETS = toOrderedAssetList(EYE_ASSET_MODULES);

/**
 * Parses the compact avatar code generated by the backend.
 * Format: "<body>.<mouth>.<eyes>" where each segment is base36.
 * Returns null when malformed so callers can fall back safely.
 */
function decodeAvatar(avatar: Avatar | string): AvatarParts | null {
  const segments = avatar.split(".");
  if (segments.length !== AVATAR_PARTS_COUNT) return null;

  const body = parseInt(segments[0] ?? "", AVATAR_BASE);
  const mouth = parseInt(segments[1] ?? "", AVATAR_BASE);
  const eyes = parseInt(segments[2] ?? "", AVATAR_BASE);

  if (Number.isNaN(body) || Number.isNaN(mouth) || Number.isNaN(eyes)) {
    return null;
  }

  return { body, mouth, eyes };
}

/**
 * Reads an asset index safely.
 * Uses modular wrap-around so out-of-range indices still resolve to a valid
 * layer, preventing hard failures if asset counts drift temporarily.
 */
function safeAssetAt(assets: readonly string[], index: number): string | null {
  if (assets.length === 0) return null;
  if (!Number.isInteger(index)) return assets[0] ?? null;

  const wrapped = ((index % assets.length) + assets.length) % assets.length;
  return assets[wrapped] ?? null;
}

/**
 * Public resolver used by `PlayerAvatar`.
 * Converts a server-sent avatar code into concrete PNG layer URLs
 * (body -> mouth -> eyes). Returns null if data is missing/invalid.
 */
export function resolvePlayerAvatarLayers(
  avatar: Avatar | string | null | undefined,
): PlayerAvatarLayers | null {
  if (!avatar) return null;

  const decoded = decodeAvatar(avatar);
  if (!decoded) return null;

  const bodySrc = safeAssetAt(BODY_ASSETS, decoded.body);
  const mouthSrc = safeAssetAt(MOUTH_ASSETS, decoded.mouth);
  const eyesSrc = safeAssetAt(EYE_ASSETS, decoded.eyes);

  if (!bodySrc || !mouthSrc || !eyesSrc) return null;

  return { bodySrc, mouthSrc, eyesSrc };
}
